safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"

siteTitle: "Commonjava"
projectTitle: " :: Configuration"
tagline: "APIs for Loading Application Configuration Data"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org